export type TypeNamesList =
  | "Base"
  | "Block"
  | "Code"
  | "Comment"
  | "CommentOperator"
  | "CommentOperatorStatement"
  | "OperatorStatementVariable"
  | "Space"
  | "StatementObject"
  | "SymbolEqual"
  | "Variable"
  | "VariableKey"
  | "VariableValue"
  | "SpaceNewLine"
  | "BlockComment"
  | "SymbolColon"
  | "SymbolExclamationMark";
