name: VSCE Publish Envuse Language Extension

on:
  push:
    tags:
      - vsce-envuse/v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.3.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login vsce
        run: echo "require('fs').writeFileSync('sample', JSON.stringify({publishers:[{name:process.env.VSCE_PUBLISHER,pat:process.env.VSCE_PERSONAL_TOKEN}]}))" | node -
        env:
          VSCE_PUBLISHER: ${{ secrets.VSCE_PUBLISHER }}
          VSCE_PERSONAL_TOKEN: ${{ secrets.VSCE_PERSONAL_TOKEN }}
      - run: npm install && npm i vsce
        working-directory: packages/envuse-vscode-syntaxes
      - name: publish vsce-envuse-language
        working-directory: packages/envuse-vscode-syntaxes
        run: npx vsce publish
